In [5]:
# ndarray 타입 생성
import numpy as np
a= np.array([1,2,3])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3])

In [7]:
print(a.shape)
print(a.ndim) #차원
print(a.dtype) #자료형
print(a.itemsize) #int64는 8바이트
print(a.size)

(3,)
1
int64
8
3


In [8]:
# type 관련

a = np.array([1,2,3] , dtype = 'int32')
b = np.array([1,2,3] , dtype = 'int64')
print(a.dtype)
print(b.dtype)
c = a + b
# 작은타입과 큰타입이 더해지면 큰타입으로 자동 업캐스팅
print(c.dtype)

int32
int64
int64


In [10]:
a = np.array([1,2,3,4])
print(a)
print(a.dtype)

print()

# type 지정하여 생성 가능
a = np.array([1,2,3,4], dtype=np.int32)
print(a.dtype)
a = np.array([1,2,3,4], dtype='int32')
print(a.dtype)

a = np.array([1,2,3]) # 1차원 ndarray 배열 생성
print(a.max()) # 가장 큰 값을 반환
print(a.min()) # 가장 작은 값을 반환
print(a.mean()) # 평균 값을 반환

[1 2 3 4]
int64

int32
int32
3
1
2.0


In [11]:
# flatten : ndarray의 모든 원소를 1차원 배열로 바꿈
a = np.array([[1,1], [2,2], [3,3]])
a
a.flatten()

array([1, 1, 2, 2, 3, 3])

In [12]:
a = np.array([1,2,3])
b = np.array([[4,5,6], [7,8,9]])
np.append(a,b)
# 2차원 배열에서 axis 0은 행, 1은 열 (3차원에서는 0은 깊이, 1은 행, 2는 열)
np.append([a], b, axis = 0) #[a]를 통해 2차원 배열로 만들어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# 난수 ndarray도 생성가능
np.random.rand(3, 3)

np.random.randint(0,10, size = 10) # 0에서 10사이의 10개의 난수생성

array([7, 9, 4, 6, 6, 8, 3, 9, 1, 6])

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
c

array([5, 7, 9])

In [15]:
a = np.array([1,2])
b = np.array([4,5,6])
c = a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [19]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,20], [30,40]])
print(a + b) # 덧셈
print(a - b)# 뺄셈
print(a * b) # 곱셈
print(a / b) # 나눗셈

[[11 22]
 [33 44]]
[[ -9 -18]
 [-27 -36]]
[[ 10  40]
 [ 90 160]]
[[0.1 0.1]
 [0.1 0.1]]


In [17]:
# 행렬 곱
print(np.matmul(a,b))
print(a @ b)

# a[0,0]*b[0,0] + a[0,1]*b[1,0]
# a[0,0]*b[0,1] + a[0,1]*b[1,1]
# a[1,0]*b[0,0] + a[1,1]*b[1,0]
# a[1,0]*b[0,1] + a[1,1]*b[1,1]

[[ 70 100]
 [150 220]]
[[ 70 100]
 [150 220]]


np.int64(220)

In [18]:
a = np.array([[1,2], [3,4]])
print(a + 1) # 행렬의 각 성분에 대한 덧셈
print(a - 1) # 행렬의 각 성분에 대한 뺄셈
print(a * 100) # 행렬의 각 성분에 대한 곱셈
print(a / 100) # 행렬의 각 성분에 대한 나눗셈
print(a **2) # 행렬의 각 성분에 대한 제곱

[[2 3]
 [4 5]]
[[0 1]
 [2 3]]
[[100 200]
 [300 400]]
[[0.01 0.02]
 [0.03 0.04]]
[[ 1  4]
 [ 9 16]]


In [20]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.full((2,3), 100))
print(np.eye(3))
print(np.random.random((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[100 100 100]
 [100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.37052475 0.34204411 0.70214169]
 [0.87606733 0.75339746 0.67495357]]


In [21]:
# np.arrange
print(np.arange(0, 10))
print(np.arange(0, 10, 2))
print(np.arange(0, 10, 3))
print(np.arange(0.0, 1.0, 0.2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[0.  0.2 0.4 0.6 0.8]


In [22]:
# linspace(a,b,c)는 a부터 b수를 c구간만큼 나눔
print(np.linspace(0, 10, 5))   #linspace = combination of the words 'linear' and 'space'
print(np.linspace(0, 10, 4))

[ 0.   2.5  5.   7.5 10. ]
[ 0.          3.33333333  6.66666667 10.        ]


In [24]:
print(np.arange(0,10).reshape(2,5)) #arange = array + range()
print(np.arange(0,10).reshape(5,2))
# print(np.arange(0,10).reshape(3,3)) # 3*3=9개여야 한다. 안그럼 에러

print(np.arange(0, 24).reshape(4, 3, 2))

a = np.arange(6).reshape(3,2)
print(a)

print(np.transpose(a))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


In [1]:
# 4-2
import numpy as np

a = np.arange(0,6).reshape(3,2)
print(a)

print(a.sum()) # 행렬의 모든 원소의 합
print(a.sum(axis = 0)) # 0축 방향(행 방향) 원소의 합
print(a.sum(axis = 1)) # 1축 방향(열 방향) 원소의 합

print(a.min(axis = 0)) # 0축 방향 원소의 최솟값
print(a.min(axis = 1)) # 1축 방향 원소의 최솟값
print(a.max(axis = 0)) # 0축 방향 원소의 최댓값
print(a.max(axis = 1)) # 1축 방향 원소의 최댓값

[[0 1]
 [2 3]
 [4 5]]
15
[6 9]
[1 5 9]
[0 1]
[0 2 4]
[4 5]
[1 3 5]


In [14]:
# np.insert는 a배열을 변경하지는 않는다.
a = np.array([1,3,4])
print(a)
print(np.insert(a,1,2))
print()
# 행의 1번째 인덱스에 4 추가하기
a = np.array([[1,1], [2,2], [3,3]])
print(a)
print(np.insert(a, 1, 4, axis = 0))
print()
# 열의 1번째 인덱스에 4 추가하기
print(np.insert(a, 1, 4, axis = 1))
print()
# -1은 뒤에서 첫번째 인덱스
a = np.array([1,2,3])
print(a[0], a[1], a[2])
print(a[-1], a[-2], a[-3])
print()
# 특정 인덱스를 지정하여 출력가능
a = np.array([1,2,3,4,5])
print(a[np.array([0,1])])
print(a[np.array([0,1,2])])
print(a[np.array([0,1,3])])
print(a[np.array([1,1,1,1])])
print(a[[0,4]]) #대충 이거랑 같은 뜻

[1 3 4]
[1 2 3 4]

[[1 1]
 [2 2]
 [3 3]]
[[1 1]
 [4 4]
 [2 2]
 [3 3]]

[[1 4 1]
 [2 4 2]
 [3 4 3]]

1 2 3
3 2 1

[1 2]
[1 2 3]
[1 2 4]
[2 2 2 2]
[1 5]


In [17]:
# 슬라이싱
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(a[1:5]) # 슬라이싱 구간 [시작:끝] 인덱스, 새로운 ndarray 객체 생성이 아닌 기존 ndarray 객체를 참조 
print(a[1:])

[20 30 40 50]
[20 30 40 50 60 70 80]


In [19]:
a = np.arange(0,6).reshape(3,2)
print(a)
print(a[0,0])
print(a[0,1])
# print(a[0,2]) #error : 0번째행의 2번째 인덱스 값이 존재 하지 않음.

[[0 1]
 [2 3]
 [4 5]]
0
1


In [20]:
a = np.arange(0,24).reshape(4, 3, 2)
print(a)
# 3차원 배열의 첫번째 깊이의 2번째 행의 1번째 열 출력
print(a[1, 2, 1])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
11


In [26]:
a = np.arange(0,24).reshape(4, 3, 2)
print(a)
print()
# 3차원 배열의 0번째 행렬 출력
print(a[0])
print()
# 3차원 배열의 0번째 행렬의 0,1,2번째 행 출력
print(a[0,0])
print(a[0,1])
print(a[0,2])
# 1차원 배열 두 개를 합침 (axis=1은 에러)
np.concatenate((a[0,0], a[0,2]), axis = 0)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

[[0 1]
 [2 3]
 [4 5]]

[0 1]
[2 3]
[4 5]


array([0, 1, 4, 5])

In [28]:
a = np.arange(0,9).reshape(3,3)
print(a)
print()

print(a[0]) # 첫 번째 행 불러오기1
print(a[0, :]) # 첫 번째 행 불러오기2
print(a[:, 0]) # 첫 번째 열 불러오기

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2]
[0 1 2]
[0 3 6]


In [31]:
print(a)
print()

# 0번째 행의 0~1컬럼
print(a[0, 0:2])
print(a[0, :2])
print()

# 0~1번째 행과 각각 0~1번째 컬럼
print(a[0:2, 0:2])
print(a[:2, :2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1]
[0 1]

[[0 1]
 [3 4]]
[[0 1]
 [3 4]]


In [34]:
print(a)
print()

print(a[1, 1:].shape)
print(a[1:2, 1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

(2,)
(1, 2)


In [35]:
# 선형 방정식 풀기, 2x+3y=1, x-2y=4 풀기
a = np.array([[2,3], [1,-2]])
b = np.array([1,4])
x = np.linalg.solve(a,b)
print(x)

[ 2. -1.]


In [36]:
# 행렬의 determinant 구하기
a = np.array([[1,2], [3,4]])
np.linalg.det(a)
b = np.array([[1,2], [3,-6]])
np.linalg.det(b)
b = np.array([[1,2], [1,2]])
np.linalg.det(b)

np.float64(0.0)